# Generated by Django 5.1.4 on 2025-03-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notecategory_note_category'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='profiles.profile'),
        ),
    ]
